#!/bin/bash
# This script belongs to CloudAseem YouTube Channel #####
# Jenkins installation on Ubuntu

# Update package index
sudo apt update -y

# Install Java (required by Jenkins)
sudo apt install fontconfig openjdk-17-jre -y

# Add Jenkins GPG key
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

# Add Jenkins package repository to the system
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null

# Update package index with Jenkins repo added
sudo apt-get update -y

# Install Jenkins
sudo apt-get install jenkins -y

# Enable Jenkins to start on boot
sudo systemctl enable jenkins

# Start Jenkins service
sudo systemctl start jenkins

# Confirmation message
echo "✅ You have successfully installed and started Jenkins on your Ubuntu system."
echo "🔑 To unlock Jenkins, run: sudo cat /var/lib/jenkins/secrets/initialAdminPassword"
